// Code Generated by Sidekick is for learning and experimentation purposes only.
/** @type {import('next').NextConfig} */
const nextConfig = {
    output: 'export',
    assetPrefix: './',
    trailingSlash: true,
  }
  
  module.exports = nextConfig
  